version: '3.9'

services:
  configfy-backend:
    build:
      context: ./backend
      args:
        platform: "linux/amd64"
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/configfydb
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: password
      SPRING_R2DBC_POOL_INITIAL_SIZE: 5
      SPRING_R2DBC_POOL_MAX_SIZE: 20
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      KEYCLOAK_REALM: configfyrealm
      KEYCLOAK_RESOURCE: configfy-backend
      KEYCLOAK_CREDENTIALS_SECRET: "ba5245cc-9ac5-4c6b-8000-836871909b3f"
    depends_on:
      - postgres
      - keycloak

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: configfydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
    command: start-dev
    ports:
      - "8081:8080"
    volumes:
      - ./scripts/init-keycloak.sh:/opt/keycloak/init-keycloak.sh
    networks:
      - default

volumes:
  pgdata:
  keycloak_data:

networks:
  default:
    driver: bridge